<?php /*

 The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://opensource.org/licenses/cpal_1.0.

 Software distributed under the License is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 The Original Code is Composr CMS.

 The Original Developer is the Initial Developer.

 The Initial Developer of the Original Code is Chris Graham.
 All portions of the code written by Chris Graham are Copyright (c) Christopher Graham. All Rights Reserved.

 See docs/LICENSE.md for full licensing information.

*/

/*
 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****
*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  Christopher Graham
 * @package    core_themeing
 */

/**
 * Hook class.
 */
class Hook_database_manifest_core_themeing
{

    /**
     * Database manifest for this addon.
     * This is automatically maintained by the software release tools if you are using it.
     *
     * @return array Map of tables, indices, foreign keys, and privileges
     */
    public function db_meta() : array
    {
        return [
            'tables' => [
                'theme_screen_tree' => [
                    'addon' => 'core_themeing',
                    'fields' => [
                        'id' => '*AUTO',
                        'json_tree' => 'LONG_TEXT',
                        'page_link' => 'SHORT_TEXT',
                    ],
                ],
                'theme_template_relations' => [
                    'addon' => 'core_themeing',
                    'fields' => [
                        'rel_a' => '*ID_TEXT',
                        'rel_b' => '*ID_TEXT',
                    ],
                ],
                'theme_images' => [
                    'addon' => 'core_themeing',
                    'fields' => [
                        'lang' => '*LANGUAGE_NAME',
                        'theme' => '*MINIID_TEXT',
                        'id' => '*SHORT_TEXT',
                        'url' => 'URLPATH',
                    ],
                ],
            ],
            'indices' => [
                'theme_images__theme' => [
                    'addon' => 'core_themeing',
                    'name' => 'theme',
                    'table' => 'theme_images',
                    'fields' => [
                        0 => 'theme',
                        1 => 'lang',
                    ],
                    'is_full_text' => false,
                ],
                'theme_screen_tree__page_link' => [
                    'addon' => 'core_themeing',
                    'name' => 'page_link',
                    'table' => 'theme_screen_tree',
                    'fields' => [
                        0 => 'page_link',
                    ],
                    'is_full_text' => false,
                ],
            ],
            'foreign_keys' => [],
            'privileges' => [],
        ];
    }
}
