<?php /*

 Composr
 Copyright (c) Christopher Graham, 2004-2024

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  Christopher Graham
 * @package    downloads
 */

/**
 * Hook class.
 */
class Hook_database_manifest_downloads
{

    /**
     * Database manifest for this addon.
     * This is automatically maintained by the software release tools if you are using it.
     *
     * @return array Map of tables, indices, foreign keys, and privileges
     */
    public function db_meta() : array
    {
        return [
            'tables' => [
                'download_categories' => [
                    'addon' => 'downloads',
                    'fields' => [
                        'id' => '*AUTO',
                        'parent_id' => '?AUTO_LINK',
                        'notes' => 'LONG_TEXT',
                        'the_description' => 'LONG_TRANS__COMCODE',
                        'category' => 'SHORT_TRANS',
                        'add_date' => 'TIME',
                        'rep_image' => 'URLPATH',
                    ],
                ],
                'download_downloads' => [
                    'addon' => 'downloads',
                    'fields' => [
                        'id' => '*AUTO',
                        'download_licence_id' => '?AUTO_LINK',
                        'out_mode_id' => '?AUTO_LINK',
                        'file_size' => '?INTEGER',
                        'edit_date' => '?TIME',
                        'validation_time' => '?TIME',
                        'category_id' => 'AUTO_LINK',
                        'allow_rating' => 'BINARY',
                        'allow_trackbacks' => 'BINARY',
                        'download_submitter_gets_points' => 'BINARY',
                        'validated' => 'BINARY',
                        'author' => 'ID_TEXT',
                        'default_pic' => 'INTEGER',
                        'download_cost' => 'INTEGER',
                        'download_views' => 'INTEGER',
                        'num_downloads' => 'INTEGER',
                        'download_data_mash' => 'LONG_TEXT',
                        'notes' => 'LONG_TEXT',
                        'additional_details' => 'LONG_TRANS__COMCODE',
                        'the_description' => 'LONG_TRANS__COMCODE',
                        'submitter' => 'MEMBER',
                        'allow_comments' => 'SHORT_INTEGER',
                        'original_filename' => 'SHORT_TEXT',
                        'name' => 'SHORT_TRANS',
                        'add_date' => 'TIME',
                        'rep_image' => 'URLPATH',
                        'url' => 'URLPATH',
                        'url_redirect' => 'URLPATH',
                    ],
                ],
                'download_licences' => [
                    'addon' => 'downloads',
                    'fields' => [
                        'id' => '*AUTO',
                        'l_text' => 'LONG_TEXT',
                        'l_title' => 'SHORT_TEXT',
                    ],
                ],
                'download_logging' => [
                    'addon' => 'downloads',
                    'fields' => [
                        'id' => '*AUTO_LINK',
                        'member_id' => '*MEMBER',
                        'ip' => 'IP',
                        'date_and_time' => 'TIME',
                    ],
                ],
            ],
            'indices' => [
                'download_categories__#category' => [
                    'addon' => 'downloads',
                    'name' => 'category',
                    'table' => 'download_categories',
                    'fields' => [
                        0 => 'category',
                    ],
                    'is_full_text' => true,
                ],
                'download_categories__#dl_cat_search__combined' => [
                    'addon' => 'downloads',
                    'name' => 'dl_cat_search__combined',
                    'table' => 'download_categories',
                    'fields' => [
                        0 => 'category',
                        1 => 'the_description',
                    ],
                    'is_full_text' => true,
                ],
                'download_categories__#the_description' => [
                    'addon' => 'downloads',
                    'name' => 'the_description',
                    'table' => 'download_categories',
                    'fields' => [
                        0 => 'the_description',
                    ],
                    'is_full_text' => true,
                ],
                'download_categories__child_find' => [
                    'addon' => 'downloads',
                    'name' => 'child_find',
                    'table' => 'download_categories',
                    'fields' => [
                        0 => 'parent_id',
                    ],
                    'is_full_text' => false,
                ],
                'download_categories__ftjoin_dccat' => [
                    'addon' => 'downloads',
                    'name' => 'ftjoin_dccat',
                    'table' => 'download_categories',
                    'fields' => [
                        0 => 'category',
                    ],
                    'is_full_text' => false,
                ],
                'download_categories__ftjoin_dcdescrip' => [
                    'addon' => 'downloads',
                    'name' => 'ftjoin_dcdescrip',
                    'table' => 'download_categories',
                    'fields' => [
                        0 => 'the_description',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__#additional_details' => [
                    'addon' => 'downloads',
                    'name' => 'additional_details',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'additional_details',
                    ],
                    'is_full_text' => true,
                ],
                'download_downloads__#dl_search__combined' => [
                    'addon' => 'downloads',
                    'name' => 'dl_search__combined',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'original_filename',
                        1 => 'download_data_mash',
                    ],
                    'is_full_text' => true,
                ],
                'download_downloads__#download_data_mash' => [
                    'addon' => 'downloads',
                    'name' => 'download_data_mash',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'download_data_mash',
                    ],
                    'is_full_text' => true,
                ],
                'download_downloads__#name' => [
                    'addon' => 'downloads',
                    'name' => 'name',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'name',
                    ],
                    'is_full_text' => true,
                ],
                'download_downloads__#original_filename' => [
                    'addon' => 'downloads',
                    'name' => 'original_filename',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'original_filename',
                    ],
                    'is_full_text' => true,
                ],
                'download_downloads__#the_description' => [
                    'addon' => 'downloads',
                    'name' => 'the_description',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'the_description',
                    ],
                    'is_full_text' => true,
                ],
                'download_downloads__category_list' => [
                    'addon' => 'downloads',
                    'name' => 'category_list',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'category_id',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__ddl' => [
                    'addon' => 'downloads',
                    'name' => 'ddl',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'download_licence_id',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__dds' => [
                    'addon' => 'downloads',
                    'name' => 'dds',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'submitter',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__downloadauthor' => [
                    'addon' => 'downloads',
                    'name' => 'downloadauthor',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'author',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__download_views' => [
                    'addon' => 'downloads',
                    'name' => 'download_views',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'download_views',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__dvalidated' => [
                    'addon' => 'downloads',
                    'name' => 'dvalidated',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'validated',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__ftjoin_dadditional' => [
                    'addon' => 'downloads',
                    'name' => 'ftjoin_dadditional',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'additional_details',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__ftjoin_ddescrip' => [
                    'addon' => 'downloads',
                    'name' => 'ftjoin_ddescrip',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'the_description',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__ftjoin_dname' => [
                    'addon' => 'downloads',
                    'name' => 'ftjoin_dname',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'name',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__recent_downloads' => [
                    'addon' => 'downloads',
                    'name' => 'recent_downloads',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'add_date',
                    ],
                    'is_full_text' => false,
                ],
                'download_downloads__top_downloads' => [
                    'addon' => 'downloads',
                    'name' => 'top_downloads',
                    'table' => 'download_downloads',
                    'fields' => [
                        0 => 'num_downloads',
                    ],
                    'is_full_text' => false,
                ],
                'download_logging__calculate_bandwidth' => [
                    'addon' => 'downloads',
                    'name' => 'calculate_bandwidth',
                    'table' => 'download_logging',
                    'fields' => [
                        0 => 'date_and_time',
                    ],
                    'is_full_text' => false,
                ],
            ],
            'foreign_keys' => [
                'download_categories__parent_id||download_categories__id' => [
                    'addon' => 'downloads',
                    'from_table' => 'download_categories',
                    'from_field' => 'parent_id',
                    'to_table' => 'download_categories',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
                'download_downloads__category_id||download_categories__id' => [
                    'addon' => 'downloads',
                    'from_table' => 'download_downloads',
                    'from_field' => 'category_id',
                    'to_table' => 'download_categories',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
                'download_downloads__download_licence_id||download_licences__id' => [
                    'addon' => 'downloads',
                    'from_table' => 'download_downloads',
                    'from_field' => 'download_licence_id',
                    'to_table' => 'download_licences',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
                'download_downloads__out_mode_id||download_downloads__id' => [
                    'addon' => 'downloads',
                    'from_table' => 'download_downloads',
                    'from_field' => 'out_mode_id',
                    'to_table' => 'download_downloads',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
                'download_logging__id||download_downloads__id' => [
                    'addon' => 'downloads',
                    'from_table' => 'download_logging',
                    'from_field' => 'id',
                    'to_table' => 'download_downloads',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
            ],
            'privileges' => [
                'autocomplete_keyword_download' => [
                    'addon' => 'downloads',
                    'section' => 'SEARCH',
                    'default' => 0,
                ],
                'autocomplete_keyword_download_category' => [
                    'addon' => 'downloads',
                    'section' => 'SEARCH',
                    'default' => 0,
                ],
                'autocomplete_title_download' => [
                    'addon' => 'downloads',
                    'section' => 'SEARCH',
                    'default' => 0,
                ],
                'autocomplete_title_download_category' => [
                    'addon' => 'downloads',
                    'section' => 'SEARCH',
                    'default' => 0,
                ],
                'download' => [
                    'addon' => 'downloads',
                    'section' => '_SECTION_DOWNLOADS',
                    'default' => 1,
                ],
            ],
        ];
    }
}
