<?php /*

 The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://opensource.org/licenses/cpal_1.0.

 Software distributed under the License is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 The Original Code is Composr CMS.

 The Original Developer is the Initial Developer.

 The Initial Developer of the Original Code is Chris Graham.
 All portions of the code written by Chris Graham are Copyright (c) Christopher Graham. All Rights Reserved.

 See docs/LICENSE.md for full licensing information.

*/

/*
 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****
*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  Christopher Graham
 * @package    ecommerce
 */

/**
 * Hook class.
 */
class Hook_database_manifest_ecommerce
{
    /**
     * Determine how we should handle database tables for things like backups, automated testing, import/export, and migration.
     *
     * @return array Map of table names to their TABLE_PURPOSE constants
     */
    public function get_table_purpose_flags() : array
    {
        require_code('database_relations');

        return [
            'f_usergroup_sub_mails' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__SUBDATA/*under f_usergroup_subs*/,
            'f_usergroup_subs' => TABLE_PURPOSE__NORMAL,
            'ecom_sales_expecting' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__FLUSHABLE_AGGRESSIVE | TABLE_PURPOSE__MISC_NO_MERGE/*too-site-tied*/,
            'ecom_trans_expecting' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__FLUSHABLE_AGGRESSIVE | TABLE_PURPOSE__MISC_NO_MERGE/*too-site-tied*/,
            'ecom_subscriptions' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__FLUSHABLE_AGGRESSIVE | TABLE_PURPOSE__SUBDATA/*under f_members*/,
            'ecom_transactions' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__FLUSHABLE_AGGRESSIVE,
            'ecom_trans_addresses' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__FLUSHABLE_AGGRESSIVE | TABLE_PURPOSE__MISC_NO_MERGE/*too-site-tied*/ | TABLE_PURPOSE__SUBDATA/*under shopping_orders*/,
            'ecom_sales' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__FLUSHABLE_AGGRESSIVE,
            'ecom_prods_custom' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__AS_COMMANDER_FS_EXTENDED_CONFIG,
            'ecom_prods_permissions' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__AS_COMMANDER_FS_EXTENDED_CONFIG,
            'ecom_prods_prices' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__AS_COMMANDER_FS_EXTENDED_CONFIG,
            'ecom_invoices' => TABLE_PURPOSE__NORMAL | TABLE_PURPOSE__FLUSHABLE_AGGRESSIVE | TABLE_PURPOSE__SUBDATA/*under f_members*/,
        ];
    }

    /**
     * Database manifest for this addon.
     * This is automatically maintained by the software release tools if you are using it.
     *
     * @return array Map of tables, indices, foreign keys, and privileges
     */
    public function db_meta() : array
    {
        return [
            'tables' => [
                'ecom_invoices' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        'i_currency' => 'ID_TEXT',
                        'i_state' => 'ID_TEXT',
                        'i_tax_code' => 'ID_TEXT',
                        'i_type_code' => 'ID_TEXT',
                        'i_note' => 'LONG_TEXT',
                        'i_tax_derivation' => 'LONG_TEXT',
                        'i_tax_tracking' => 'LONG_TEXT',
                        'i_member_id' => 'MEMBER',
                        'i_price' => 'REAL',
                        'i_tax' => 'REAL',
                        'i_item_name' => 'SHORT_TEXT',
                        'i_processing_code' => 'SHORT_TEXT',
                        'i_time' => 'TIME',
                    ],
                ],
                'ecom_prods_custom' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        'c_price_points' => '?INTEGER',
                        'c_price' => '?REAL',
                        'c_enabled' => 'BINARY',
                        'c_one_per_member' => 'BINARY',
                        'c_tax_code' => 'ID_TEXT',
                        'c_mail_body' => 'LONG_TRANS',
                        'c_description' => 'LONG_TRANS__COMCODE',
                        'c_shipping_cost' => 'REAL',
                        'c_mail_subject' => 'SHORT_TRANS',
                        'c_title' => 'SHORT_TRANS',
                        'c_image_url' => 'URLPATH',
                    ],
                ],
                'ecom_prods_permissions' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        'p_hours' => '?INTEGER',
                        'p_price_points' => '?INTEGER',
                        'p_price' => '?REAL',
                        'p_enabled' => 'BINARY',
                        'p_category' => 'ID_TEXT',
                        'p_module' => 'ID_TEXT',
                        'p_page' => 'ID_TEXT',
                        'p_privilege' => 'ID_TEXT',
                        'p_tax_code' => 'ID_TEXT',
                        'p_type' => 'ID_TEXT',
                        'p_zone' => 'ID_TEXT',
                        'p_mail_body' => 'LONG_TRANS',
                        'p_description' => 'LONG_TRANS__COMCODE',
                        'p_mail_subject' => 'SHORT_TRANS',
                        'p_title' => 'SHORT_TRANS',
                    ],
                ],
                'ecom_sales' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        'txn_id' => 'ID_TEXT',
                        'member_id' => 'MEMBER',
                        'details' => 'SHORT_TEXT',
                        'details2' => 'SHORT_TEXT',
                        'date_and_time' => 'TIME',
                    ],
                ],
                'ecom_sales_expecting' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        'e_details' => 'LONG_TEXT',
                        'e_time' => 'TIME',
                    ],
                ],
                'ecom_subscriptions' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        's_auto_fund_source' => 'ID_TEXT',
                        's_currency' => 'ID_TEXT',
                        's_payment_gateway' => 'ID_TEXT',
                        's_purchase_id' => 'ID_TEXT',
                        's_state' => 'ID_TEXT',
                        's_tax_code' => 'ID_TEXT',
                        's_type_code' => 'ID_TEXT',
                        's_length' => 'INTEGER',
                        's_tax_derivation' => 'LONG_TEXT',
                        's_tax_tracking' => 'LONG_TEXT',
                        's_member_id' => 'MEMBER',
                        's_price' => 'REAL',
                        's_tax' => 'REAL',
                        's_auto_fund_key' => 'SHORT_TEXT',
                        's_length_units' => 'SHORT_TEXT',
                        's_time' => 'TIME',
                    ],
                ],
                'ecom_trans_addresses' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        'a_trans_expecting_id' => 'ID_TEXT',
                        'a_txn_id' => 'ID_TEXT',
                        'a_street_address' => 'LONG_TEXT',
                        'a_city' => 'SHORT_TEXT',
                        'a_country' => 'SHORT_TEXT',
                        'a_county' => 'SHORT_TEXT',
                        'a_email' => 'SHORT_TEXT',
                        'a_firstname' => 'SHORT_TEXT',
                        'a_lastname' => 'SHORT_TEXT',
                        'a_phone' => 'SHORT_TEXT',
                        'a_post_code' => 'SHORT_TEXT',
                        'a_state' => 'SHORT_TEXT',
                    ],
                ],
                'f_usergroup_subs' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        's_auto_recur' => 'BINARY',
                        's_enabled' => 'BINARY',
                        's_uses_primary' => 'BINARY',
                        's_group_id' => 'GROUP',
                        's_tax_code' => 'ID_TEXT',
                        's_length' => 'INTEGER',
                        's_mail_end' => 'LONG_TRANS',
                        's_mail_start' => 'LONG_TRANS',
                        's_mail_uhoh' => 'LONG_TRANS',
                        's_description' => 'LONG_TRANS__COMCODE',
                        's_price' => 'REAL',
                        's_length_units' => 'SHORT_TEXT',
                        's_title' => 'SHORT_TRANS',
                    ],
                ],
                'f_usergroup_sub_mails' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*AUTO',
                        'm_usergroup_sub_id' => 'AUTO_LINK',
                        'm_ref_point' => 'ID_TEXT',
                        'm_ref_point_offset' => 'INTEGER',
                        'm_body' => 'LONG_TRANS',
                        'm_subject' => 'SHORT_TRANS',
                    ],
                ],
                'ecom_prods_prices' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'name' => '*ID_TEXT',
                        'price_points' => '?INTEGER',
                        'price' => '?REAL',
                        'tax_code' => 'ID_TEXT',
                    ],
                ],
                'ecom_transactions' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*ID_TEXT',
                        't_time' => '*TIME',
                        't_currency' => 'ID_TEXT',
                        't_parent_txn_id' => 'ID_TEXT',
                        't_payment_gateway' => 'ID_TEXT',
                        't_purchase_id' => 'ID_TEXT',
                        't_session_id' => 'ID_TEXT',
                        't_type_code' => 'ID_TEXT',
                        't_invoicing_breakdown' => 'LONG_TEXT',
                        't_memo' => 'LONG_TEXT',
                        't_tax_derivation' => 'LONG_TEXT',
                        't_tax_tracking' => 'LONG_TEXT',
                        't_member_id' => 'MEMBER',
                        't_price' => 'REAL',
                        't_shipping' => 'REAL',
                        't_tax' => 'REAL',
                        't_transaction_fee' => 'REAL',
                        't_pending_reason' => 'SHORT_TEXT',
                        't_reason' => 'SHORT_TEXT',
                        't_status' => 'SHORT_TEXT',
                    ],
                ],
                'ecom_trans_expecting' => [
                    'addon' => 'ecommerce',
                    'fields' => [
                        'id' => '*ID_TEXT',
                        'e_length' => '?INTEGER',
                        'e_currency' => 'ID_TEXT',
                        'e_length_units' => 'ID_TEXT',
                        'e_purchase_id' => 'ID_TEXT',
                        'e_session_id' => 'ID_TEXT',
                        'e_type_code' => 'ID_TEXT',
                        'e_price_points' => 'INTEGER',
                        'e_ip_address' => 'IP',
                        'e_invoicing_breakdown' => 'LONG_TEXT',
                        'e_memo' => 'LONG_TEXT',
                        'e_tax_derivation' => 'LONG_TEXT',
                        'e_tax_tracking' => 'LONG_TEXT',
                        'e_member_id' => 'MEMBER',
                        'e_price' => 'REAL',
                        'e_shipping' => 'REAL',
                        'e_tax' => 'REAL',
                        'e_item_name' => 'SHORT_TEXT',
                        'e_time' => 'TIME',
                    ],
                ],
            ],
            'indices' => [
                'ecom_invoices__i_member_id' => [
                    'addon' => 'ecommerce',
                    'name' => 'i_member_id',
                    'table' => 'ecom_invoices',
                    'fields' => [
                        0 => 'i_member_id',
                    ],
                    'is_full_text' => false,
                ],
                'ecom_prods_custom__#c_description' => [
                    'addon' => 'ecommerce',
                    'name' => 'c_description',
                    'table' => 'ecom_prods_custom',
                    'fields' => [
                        0 => 'c_description',
                    ],
                    'is_full_text' => true,
                ],
                'ecom_prods_custom__#c_mail_body' => [
                    'addon' => 'ecommerce',
                    'name' => 'c_mail_body',
                    'table' => 'ecom_prods_custom',
                    'fields' => [
                        0 => 'c_mail_body',
                    ],
                    'is_full_text' => true,
                ],
                'ecom_prods_custom__#c_mail_subject' => [
                    'addon' => 'ecommerce',
                    'name' => 'c_mail_subject',
                    'table' => 'ecom_prods_custom',
                    'fields' => [
                        0 => 'c_mail_subject',
                    ],
                    'is_full_text' => true,
                ],
                'ecom_prods_custom__#c_title' => [
                    'addon' => 'ecommerce',
                    'name' => 'c_title',
                    'table' => 'ecom_prods_custom',
                    'fields' => [
                        0 => 'c_title',
                    ],
                    'is_full_text' => true,
                ],
                'ecom_prods_permissions__#p_description' => [
                    'addon' => 'ecommerce',
                    'name' => 'p_description',
                    'table' => 'ecom_prods_permissions',
                    'fields' => [
                        0 => 'p_description',
                    ],
                    'is_full_text' => true,
                ],
                'ecom_prods_permissions__#p_mail_body' => [
                    'addon' => 'ecommerce',
                    'name' => 'p_mail_body',
                    'table' => 'ecom_prods_permissions',
                    'fields' => [
                        0 => 'p_mail_body',
                    ],
                    'is_full_text' => true,
                ],
                'ecom_prods_permissions__#p_mail_subject' => [
                    'addon' => 'ecommerce',
                    'name' => 'p_mail_subject',
                    'table' => 'ecom_prods_permissions',
                    'fields' => [
                        0 => 'p_mail_subject',
                    ],
                    'is_full_text' => true,
                ],
                'ecom_prods_permissions__#p_title' => [
                    'addon' => 'ecommerce',
                    'name' => 'p_title',
                    'table' => 'ecom_prods_permissions',
                    'fields' => [
                        0 => 'p_title',
                    ],
                    'is_full_text' => true,
                ],
                'ecom_sales__member_id' => [
                    'addon' => 'ecommerce',
                    'name' => 'member_id',
                    'table' => 'ecom_sales',
                    'fields' => [
                        0 => 'member_id',
                    ],
                    'is_full_text' => false,
                ],
                'ecom_subscriptions__s_member_id' => [
                    'addon' => 'ecommerce',
                    'name' => 's_member_id',
                    'table' => 'ecom_subscriptions',
                    'fields' => [
                        0 => 's_member_id',
                    ],
                    'is_full_text' => false,
                ],
                'ecom_transactions__t_time' => [
                    'addon' => 'ecommerce',
                    'name' => 't_time',
                    'table' => 'ecom_transactions',
                    'fields' => [
                        0 => 't_time',
                    ],
                    'is_full_text' => false,
                ],
                'ecom_transactions__t_type_code' => [
                    'addon' => 'ecommerce',
                    'name' => 't_type_code',
                    'table' => 'ecom_transactions',
                    'fields' => [
                        0 => 't_type_code',
                    ],
                    'is_full_text' => false,
                ],
                'ecom_trans_addresses__trans_expecting_id' => [
                    'addon' => 'ecommerce',
                    'name' => 'trans_expecting_id',
                    'table' => 'ecom_trans_addresses',
                    'fields' => [
                        0 => 'a_trans_expecting_id',
                    ],
                    'is_full_text' => false,
                ],
                'ecom_trans_addresses__txn_id' => [
                    'addon' => 'ecommerce',
                    'name' => 'txn_id',
                    'table' => 'ecom_trans_addresses',
                    'fields' => [
                        0 => 'a_txn_id',
                    ],
                    'is_full_text' => false,
                ],
                'f_usergroup_subs__#s_description' => [
                    'addon' => 'ecommerce',
                    'name' => 's_description',
                    'table' => 'f_usergroup_subs',
                    'fields' => [
                        0 => 's_description',
                    ],
                    'is_full_text' => true,
                ],
                'f_usergroup_subs__#s_mail_end' => [
                    'addon' => 'ecommerce',
                    'name' => 's_mail_end',
                    'table' => 'f_usergroup_subs',
                    'fields' => [
                        0 => 's_mail_end',
                    ],
                    'is_full_text' => true,
                ],
                'f_usergroup_subs__#s_mail_start' => [
                    'addon' => 'ecommerce',
                    'name' => 's_mail_start',
                    'table' => 'f_usergroup_subs',
                    'fields' => [
                        0 => 's_mail_start',
                    ],
                    'is_full_text' => true,
                ],
                'f_usergroup_subs__#s_mail_uhoh' => [
                    'addon' => 'ecommerce',
                    'name' => 's_mail_uhoh',
                    'table' => 'f_usergroup_subs',
                    'fields' => [
                        0 => 's_mail_uhoh',
                    ],
                    'is_full_text' => true,
                ],
                'f_usergroup_subs__#s_title' => [
                    'addon' => 'ecommerce',
                    'name' => 's_title',
                    'table' => 'f_usergroup_subs',
                    'fields' => [
                        0 => 's_title',
                    ],
                    'is_full_text' => true,
                ],
                'f_usergroup_sub_mails__#m_body' => [
                    'addon' => 'ecommerce',
                    'name' => 'm_body',
                    'table' => 'f_usergroup_sub_mails',
                    'fields' => [
                        0 => 'm_body',
                    ],
                    'is_full_text' => true,
                ],
                'f_usergroup_sub_mails__#m_subject' => [
                    'addon' => 'ecommerce',
                    'name' => 'm_subject',
                    'table' => 'f_usergroup_sub_mails',
                    'fields' => [
                        0 => 'm_subject',
                    ],
                    'is_full_text' => true,
                ],
            ],
            'foreign_keys' => [
                'ecom_prods_permissions__p_page||modules__module_the_name' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'ecom_prods_permissions',
                    'from_field' => 'p_page',
                    'to_table' => 'modules',
                    'to_field' => 'module_the_name',
                    'special_values' => [],
                ],
                'ecom_prods_permissions__p_privilege||privilege_list__the_name' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'ecom_prods_permissions',
                    'from_field' => 'p_privilege',
                    'to_table' => 'privilege_list',
                    'to_field' => 'the_name',
                    'special_values' => [],
                ],
                'ecom_prods_permissions__p_zone||zones__zone_name' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'ecom_prods_permissions',
                    'from_field' => 'p_zone',
                    'to_table' => 'zones',
                    'to_field' => 'zone_name',
                    'special_values' => [],
                ],
                'ecom_transactions__t_parent_txn_id||ecom_transactions__id' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'ecom_transactions',
                    'from_field' => 't_parent_txn_id',
                    'to_table' => 'ecom_transactions',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
                'ecom_transactions__t_session_id||sessions__the_session' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'ecom_transactions',
                    'from_field' => 't_session_id',
                    'to_table' => 'sessions',
                    'to_field' => 'the_session',
                    'special_values' => [],
                ],
                'ecom_trans_addresses__a_trans_expecting_id||ecom_trans_expecting__id' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'ecom_trans_addresses',
                    'from_field' => 'a_trans_expecting_id',
                    'to_table' => 'ecom_trans_expecting',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
                'ecom_trans_addresses__a_txn_id||ecom_transactions__id' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'ecom_trans_addresses',
                    'from_field' => 'a_txn_id',
                    'to_table' => 'ecom_transactions',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
                'ecom_trans_expecting__e_session_id||sessions__the_session' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'ecom_trans_expecting',
                    'from_field' => 'e_session_id',
                    'to_table' => 'sessions',
                    'to_field' => 'the_session',
                    'special_values' => [],
                ],
                'f_usergroup_sub_mails__m_usergroup_sub_id||f_usergroup_subs__id' => [
                    'addon' => 'ecommerce',
                    'from_table' => 'f_usergroup_sub_mails',
                    'from_field' => 'm_usergroup_sub_id',
                    'to_table' => 'f_usergroup_subs',
                    'to_field' => 'id',
                    'special_values' => [],
                ],
            ],
            'privileges' => [
                'access_ecommerce_in_test_mode' => [
                    'addon' => 'ecommerce',
                    'section' => 'ECOMMERCE',
                    'default' => 0,
                ],
            ],
        ];
    }
}
