<?php /*

 The contents of this file are subject to the Common Public Attribution License Version 1.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://opensource.org/licenses/cpal_1.0.

 Software distributed under the License is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
 See the License for the specific language governing rights and limitations under the License.

 The Original Code is Composr CMS.

 The Original Developer is the Initial Developer.

 The Initial Developer of the Original Code is Chris Graham.
 All portions of the code written by Chris Graham are Copyright (c) Christopher Graham. All Rights Reserved.

 See docs/LICENSE.md for full licensing information.

*/

/*
 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****
*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  Christopher Graham
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_directive_FRACTIONAL_EDITABLE
{
    /**
     * Get information about this directive.
     *
     * @return ?array Array of information (null: hook disabled)
     */
    public function info() : ?array
    {
        return [];
    }

    /**
     * Run function for directive hooks.
     *
     * @param  string $value The value, passed by reference
     * @param  array $param Directive parameters
     * @param  string $lang The language to evaluate this directive in (some directives refer to language elements)
     * @param  array $escaped Array of escaping operations
     * @param  ID_TEXT $template_name The name of the template this came from (blank: not from a file / unknown)
     */
    public function run(string &$value, array $param, string $lang, array $escaped, string $template_name)
    {
        require_javascript('fractional_edit');

        foreach (array_keys($param) as $key) {
            if (!is_numeric($key)) {
                unset($param[$key]);
            }
        }
        if (isset($param[3])) {
            $edit_text = $param[0]->evaluate();
            $edit_param_name = $param[1]->evaluate();
            $edit_page_link = $param[2]->evaluate();
            $supports_comcode = (isset($param[4]) ? $param[3]->evaluate() : '0') === '1';
            $explicit_editing_links = (isset($param[5]) ? $param[4]->evaluate() : '0') === '1';
            $has_permission = (isset($param[6]) ? ($param[5]->evaluate() === '1') : null);

            list($zone, $attributes,) = page_link_decode($edit_page_link);
            if ($zone === '_SEARCH') {
                $zone = get_module_zone($attributes['page']);
            }
            if (
                (get_option('fractional_editing') == '1') &&
                (has_actual_page_access(get_member(), $attributes['page'], $zone)) &&
                (($has_permission === true) || (($has_permission === null) && (has_zone_access(get_member(), 'adminzone'))))
            ) {
                $keep = symbol_tempcode('KEEP');
                $url = find_script('fractional_edit') . '?edit_param_name=' . urlencode($edit_param_name) . '&supports_comcode=' . ($supports_comcode ? '1' : '0') . '&zone=' . urlencode($zone) . $keep->evaluate();
                if (!empty($attributes)) {
                    $url .= '&' . http_build_query($attributes);
                }

                $_value = $param[count($param) - 1];
                $_value = do_template('FRACTIONAL_EDIT', [
                    '_GUID' => '075ac126c427d28b309004bc67b32b08',
                    'VALUE' => $_value,
                    'URL' => $url,
                    'EDIT_TEXT' => $edit_text,
                    'EDIT_PARAM_NAME' => $edit_param_name,
                    'EXPLICIT_EDITING_LINKS' => $explicit_editing_links,
                ]);
                $value = $_value->evaluate();
            } else {
                $value = $param[count($param) - 1]->evaluate();
            }
        }
    }
}
