<?php /*

 Composr
 Copyright (c) Christopher Graham, 2004-2024

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  Christopher Graham
 * @package    stats
 */

/**
 * Hook class.
 */
class Hook_cron_stats_preprocess_raw_data
{
    protected const END_TIME_CUTOFF = 60 * 60; // Only process up to one hour at a time to avoid server freezes.
    protected const INITIAL_BACK_TIME = 24 * 60 * 60 * 31; // Don't calculate stats older than 31 days ago to prevent server freezes.

    /**
     * Get info from this hook.
     *
     * @param  ?TIME $last_run Last time run (null: never)
     * @param  ?boolean $calculate_num_queued Calculate the number of items queued, if possible (null: the hook may decide / low priority)
     * @return ?array Return a map of info about the hook (null: disabled)
     */
    public function info(?int $last_run, ?bool $calculate_num_queued) : ?array
    {
        if (!addon_installed('stats')) {
            return null;
        }

        return [
            'label' => 'Stats preprocessing',
            'num_queued' => null,
            'minutes_between_runs' => 1,
            'enabled_by_default' => true,
        ];
    }

    /**
     * Run function for system scheduler hooks. Searches for tasks to perform.
     */
    public function run()
    {
        $start_time = null;

        // LEGACY: 11.beta9
        $_start_time = get_value('stats__last_processed', null, true);
        if ($_start_time !== null) {
            delete_value('stats__last_processed', true);
            $GLOBALS['SITE_DB']->query_delete('stats_preprocessed');
            $GLOBALS['SITE_DB']->query_delete('stats_preprocessed_flat');
        }

        $hook_start = time();

        require_code('global3');

        // Determine if we are in need of processing deltas; these are done first
        $pending_deltas = $GLOBALS['SITE_DB']->query_select_value('stats_preprocessed_delta', 'COUNT(*)');
        $doing_deltas = ($pending_deltas > 0);

        if ($doing_deltas) {
            cms_profile_start_for('Hook_cron_stats_preprocess_raw_data deltas');

            push_query_limiting(false);

            while ((memory_get_usage() < (1024 * 1024 * 32)) && ((time() - $hook_start) < 15)) { // Time and memory checks
                $row = $GLOBALS['SITE_DB']->query_select('stats_preprocessed_delta', ['*'], [], ' ORDER BY id', 1);
                if (!array_key_exists(0, $row)) { // No more to do
                    break;
                }

                $stats_row = $GLOBALS['SITE_DB']->query_select('stats_preprocessed', ['*'], [
                    'p_bucket' => $row[0]['p_bucket'],
                    'p_pivot' => $row[0]['p_pivot'],
                    'p_pivot_interval' => $row[0]['p_pivot_interval'],
                    'p_pivot_value' => $row[0]['p_pivot_value'],
                ], '', 1);

                if (!array_key_exists(0, $stats_row)) {
                    $GLOBALS['SITE_DB']->query_insert('stats_preprocessed', [
                        'p_bucket' => $row[0]['p_bucket'],
                        'p_pivot' => $row[0]['p_pivot'],
                        'p_pivot_interval' => $row[0]['p_pivot_interval'],
                        'p_pivot_value' => $row[0]['p_pivot_value'],
                        'p_data' => $row[0]['p_data'],
                    ]);
                } else {
                    $row_u = @unserialize($row[0]['p_data']);
                    if ($row_u === false) {
                        warn_exit(do_lang_tempcode('INTERNAL_ERROR'), escape_html('TODO'));
                    }

                    $stats_row_u = @unserialize($stats_row[0]['p_data']);
                    if ($stats_row_u === false) {
                        warn_exit(do_lang_tempcode('INTERNAL_ERROR'), escape_html('TODO'));
                    }

                    $this->stats_deep_merge($stats_row_u, $row_u);

                    $GLOBALS['SITE_DB']->query_update('stats_preprocessed', ['p_data' => serialize($stats_row_u)], [
                        'p_bucket' => $row[0]['p_bucket'],
                        'p_pivot' => $row[0]['p_pivot'],
                        'p_pivot_interval' => $row[0]['p_pivot_interval'],
                        'p_pivot_value' => $row[0]['p_pivot_value'],
                    ]);
                }

                $GLOBALS['SITE_DB']->query_delete('stats_preprocessed_delta', ['id' => $row[0]['id']]);

                unset($row);
                unset($row_u);
                unset($stats_row);
                unset($stats_row_u);
                unset($merged_data);
            }

            pop_query_limiting();

            cms_profile_end_for('Hook_cron_stats_preprocess_raw_data preprocess_raw_data_for');
        }

        // Memory and time check
        if ((memory_get_usage() >= (1024 * 1024 * 32)) || ((time() - $hook_start) >= 15)) {
            return;
        }

        cms_profile_start_for('Hook_cron_stats_preprocess_raw_data preprocess_raw_data_for');

        push_query_limiting(false);
        disable_php_memory_limit();

        require_code('stats');
        require_lang('stats');

        $hook_obs = array_keys(find_all_hooks('modules', 'admin_stats'));
        cms_shuffle_assoc($hook_obs);

        foreach ($hook_obs as $hook_name) {
            $_start_time = get_value('stats__last_processed__' . $hook_name, null, true);
            if ($_start_time === null) {
                require_code('global4');
                $start_time = get_site_start_time();
            } else {
                $start_time = intval($_start_time);
            }

            // Do not process too far back
            if ($start_time < (time() - self::INITIAL_BACK_TIME)) {
                $start_time = (time() - self::INITIAL_BACK_TIME);
            }

            /*
                NB: We subtract 1 second due to an edge case; the current second is not over yet, so additional stats (especially views)
                that happen this second might later get logged. If we process this second now, those views / stats might get neglected.
            */
            $end_time = (time() - 1);

            // Do not process too much at once
            if (($end_time - $start_time) > self::END_TIME_CUTOFF) {
                $end_time = ($start_time + self::END_TIME_CUTOFF);
            }

            preprocess_raw_data_for($hook_name, $start_time, $end_time);

            set_value('stats__last_processed__' . $hook_name, strval($end_time), true);

            // Memory and time check
            if ((memory_get_usage() >= (1024 * 1024 * 60)) || ((time() - $hook_start) >= 15)) {
                break;
            }
        }

        // Send KPI notifications...

        send_kpi_notifications();

        pop_query_limiting();

        cms_profile_end_for('Hook_cron_stats_preprocess_raw_data preprocess_raw_data_for');
    }

    /**
     * Deep-merge two statistics arrays.
     *
     * @param  mixed $base The base statistics, passed and modified by reference
     * @param  mixed $delta The statistics we are merging into $base
     */
    protected function stats_deep_merge(&$base, $delta)
    {
        // Sanity check: $base and $delta must both be arrays or both not be arrays
        if (is_array($base) && !is_array($delta)) {
            warn_exit(do_lang_tempcode('INTERNAL_ERROR'), escape_html('TODO'));
        }
        if (!is_array($base) && is_array($delta)) {
            warn_exit(do_lang_tempcode('INTERNAL_ERROR'), escape_html('TODO'));
        }

        if (!is_array($delta)) {
            if (is_numeric($delta)) { // Numbers get added together (counters)
                $base = $base + $delta;
            } else { // All other types overwrite previous values
                $base = $delta;
            }
            return;
        }

        foreach ($delta as $k => $v) {
            // Does not exist on base? Create it!
            if (!array_key_exists($k, $base)) {
                $base[$k] = $v;
                continue;
            }

            if (is_array($v)) { // Arrays get merged
                $this->stats_deep_merge($base[$k], $v);
            } elseif (is_numeric($v)) { // Numbers get added together (counters)
                $base[$k] = $base[$k] + $v;
            } else { // All other types overwrite previous values
                $base[$k] = $v;
            }
        }
    }
}
