<?php /*

 Composr
 Copyright (c) Christopher Graham, 2004-2024

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  Christopher Graham
 * @package    core
 */

/**
 * Hook class.
 */
class Hook_symbol_BLOCK
{
    /**
     * Get information about this symbol.
     *
     * @return ?array Array of information (null: hook disabled)
     */
    public function info() : ?array
    {
        return [
            'compile' => SYMBOL_COMPILE_STATIC_NONE,
        ];
    }

    /**
     * Run function for symbol hooks. Searches for tasks to perform.
     *
     * @param  array $param Symbol parameters
     * @param  string $lang The language to evaluate this symbol in (some symbols refer to language elements)
     * @param  array $escaped Array of escaping operations
     * @return string Result
     */
    public function run(array $param, string $lang, array $escaped) : string
    {
        if (!$GLOBALS['STATIC_TEMPLATE_TEST_MODE']) { // Normal operation
            $temp_array = [];
            handle_symbol_preprocessing([$escaped, TC_SYMBOL, 'BLOCK', $param], $temp_array); // Late preprocessing. Should not be needed in case of full screen output (as this was properly preprocessed), but is in other cases

            foreach ($param as $i => $p) {
                if (is_object($p)) {
                    $param[$i] = $p->evaluate();
                }
            }

            if ((count($param) == 1) && (strpos($param[0], ',') !== false)) { // NB: This code is also in Tempcode.php
                $param_2 = comma_list_str_to_arr($param[0], true);
            } else {
                $param_2 = $param;
            }

            foreach ($param_2 as &$_param) {
                $_param = preg_replace('#^\s*([^\s]+)\s*=#', '$1=', $_param);
            }

            if ((in_array('defer=1', $param_2)) && (!running_script('comcode_convert'))) {
                $value = static_evaluate_tempcode(do_template('JS_BLOCK', [
                    '_GUID' => '2334719e23b2773ad04fe0fcbdce684d',
                    'BLOCK_PARAMS' => comma_list_arr_to_str($param_2),
                    'SELF_URL' => get_self_url(),
                ]));
            } else {
                global $BLOCKS_CACHE;
                if (isset($BLOCKS_CACHE[serialize($param_2)])) { // Will always be set
                    $value = $BLOCKS_CACHE[serialize($param_2)]->evaluate();
                } else {
                    $value = '';
                    if ($GLOBALS['XSS_DETECT']) {
                        ocp_mark_as_escaped($value);
                    }
                }
            }
        } else {
            $value = '';
            if ($GLOBALS['XSS_DETECT']) {
                ocp_mark_as_escaped($value);
            }
        }

        return $value;
    }
}

