<?php /*

 Composr
 Copyright (c) Christopher Graham, 2004-2024

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  Christopher Graham
 * @package    core_privacy
 */

/**
 * Hook class.
 */
class Hook_symbol_COOKIE_DATA_JSON
{
    /**
     * Get information about this symbol.
     *
     * @return ?array Array of information (null: hook disabled)
     */
    public function info() : ?array
    {
        return [
            'compile' => SYMBOL_COMPILE_STATIC_SAFE,
        ];
    }

    /**
     * Run function for symbol hooks. Searches for tasks to perform.
     *
     * @param  array $param Symbol parameters
     * @param  string $lang The language to evaluate this symbol in (some symbols refer to language elements)
     * @param  array $escaped Array of escaping operations
     * @return string Result
     */
    public function run(array $param, string $lang, array $escaped) : string
    {
        $value = '{}';

        if (running_script('install')) {
            return $value;
        }

        if (function_exists('find_all_hook_obs')) {
            $_value = [];

            require_code('privacy');

            $hook_obs = find_all_hook_obs('systems', 'privacy', 'Hook_privacy_');
            foreach ($hook_obs as $hook => $hook_ob) {
                $info = $hook_ob->info();

                if ($info === null) {
                    continue;
                }

                foreach ($info['cookies'] as $name => $cookie_info) {
                    if (($cookie_info === null) || !isset($cookie_info['category'])) {
                        continue;
                    }

                    // In JavaScript, we will be treating this string as a regular expression. We need to escape expressions except the wildcard.
                    $_value[$cookie_info['category']][] = str_replace('\*', '.*', preg_quote($name, '/'));
                }
            }

            $value = @json_encode($_value);
            if ($value === false) {
                $value = '{}';
            }
        }

        return $value;
    }
}

