<?php /*

 Composr
 Copyright (c) Christopher Graham, 2004-2024

 See docs/LICENSE.md for full licensing information.


 NOTE TO PROGRAMMERS:
   Do not edit this file. If you need to make changes, save your changed file to the appropriate *_custom folder
   **** If you ignore this advice, then your website upgrades (e.g. for bug fixes) will likely kill your changes ****

*/

/**
 * @license    http://opensource.org/licenses/cpal_1.0 Common Public Attribution License
 * @copyright  Christopher Graham
 * @package    bayes_antispam
 */

/**
 * Hook class.
 */
class Hook_task_bayes_antispam
{
    /**
     * Run the task hook.
     *
     * @param  array $categories Train the data on the specified categories
     * @param  ID_TEXT $content_type The content type to train
     * @param  ID_TEXT $content_id The content ID to train
     * @param  MEMBER $member_id The owner of the content, used to determine language (null: use site default)
     * @param  ?array $old_content If editing, the old antispam-style content to be untrained (null: new content)
     * @return ?array A tuple of at least 2: Return mime-type, content (either Tempcode, or a string, or a filename and file-path pair to a temporary file), map of HTTP headers if transferring immediately, map of ini_set commands if transferring immediately (null: show standard success message)
     */
    public function run(array $categories, string $content_type, string $content_id, ?int $member_id, ?array $old_content = null) : ?array
    {
        if (!addon_installed('bayes_antispam')) {
            return null;
        }
        if (!addon_installed('bayes_common')) {
            return null;
        }

        require_code('antispam2');

        // Untrain old content, but only if we actually trained on this content before
        if ($old_content !== null) {
            $lang = $GLOBALS['SITE_DB']->query_select_value_if_there('antispam_bayes_trained', 't_lang', ['t_content_type' => $content_type, 't_content_id' => $content_id]);
            if ($lang !== null) {
                $bayes_model = load_bayes_antispam(null, $lang);
                if ($bayes_model === null) {
                    return null;
                }

                $old_categories = explode("\n", $GLOBALS['SITE_DB']->query_select_value('antispam_bayes_trained', 't_categories', ['t_content_type' => $content_type, 't_content_id' => $content_id]));

                foreach ($old_content as $line) {
                    $bayes_model->train($line, $old_categories, true);
                }
                $GLOBALS['SITE_DB']->query_delete('antispam_bayes_trained', ['t_content_type' => $content_type, 't_content_id' => $content_id]);
            }
        }

        // Integrity check: we should never end up trying to re-train the same content ($old_content should have been specified, which would have deleted this DB row above)
        $test = $GLOBALS['SITE_DB']->query_select_value_if_there('antispam_bayes_trained', 't_date_and_time', ['t_content_type' => $content_type, 't_content_id' => $content_id]);
        if ($test !== null) {
            return null;
        }

        // Load model in the language to train
        $bayes_model = load_bayes_antispam($member_id);
        if ($bayes_model === null) {
            return null;
        }

        // Train new content (if it exists and is time to be trained)
        $content = content_get_antispam_data($content_type, $content_id, true);
        foreach ($content as $line) {
            $bayes_model->train($line, $categories);
        }
        if (count($content) > 0) {
            $GLOBALS['SITE_DB']->query_insert('antispam_bayes_trained', ['t_date_and_time' => time(), 't_content_id' => $content_id, 't_content_type' => $content_type, 't_lang' => $bayes_model->get_lang(), 't_categories' => implode("\n", $categories)]);
        }

        return null;
    }
}
